### ISSUE TITLE
Invocation with a global variable can't be imported in Moose 10

### ISSUE THREAD

**Issue by maelpaul** [fuhrmanator/FamixTypeScriptImporter#1]
Example of TypeScript code which leads to the bug:
  
class AAA {
    public method(): void {}
}

const x1 = new AAA();
x1.method();

The x1.method invocation can be parsed with the importer but, then, when trying to import the JSON file in Moose, the invocation receiver is AAA, which is good, but the sender is set to nil, which causes the failure of the importation.

**Comment by fuhrmanator** [comment]
Hopefully, with the new metamodel, a Script (or Module) can be a sender.
