### ISSUE TITLE
ImportClause entities don't have valid sourceAnchor info

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/FamixTypeScriptImporter#27]
V1.0.17: There are no fields like fileName, startPos, endPos, etc.

Should ImportClause entities have IndexedFileAnchor entities?

![image](https://github.com/fuhrmanator/FamixTypeScriptImporter/assets/7606540/d9648ae5-c38c-445a-9a3f-56dd54e5f705)

**Comment by fuhrmanator** [comment]
Should check to see what Java imports look like.

**Comment by fuhrmanator** [comment]
> Should check to see what Java imports look like.

I couldn't see any FamixJavaImport, at least for a model generated by VerveineJ 2.0.4 (with @badetitou's docker).

I suspect the source should just be the "import ..." line.

**Comment by badetitou** [comment]
In FamixJava Model. The import does not exist. There is no FamixJavaImport ( as far as I know )


Thus, it is not imported
